apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "k8s-pod-killer.fullname" . }}
  labels:
    {{- include "k8s-pod-killer.labels" . | nindent 4 }}
data:
{{- range $k, $v := .Values.env }}
  {{ $k | upper | quote }}: {{ $v | quote }}
{{- end }}

