name: Go

on: [push]

jobs:
  build:
    strategy:
      matrix:
        os: [linux]
        arch: [amd64, arm64]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.24
          cache-dependency-path: go.sum
      - name: Install dependencies
        run: go get .
      - name: Build
        env:
          GOOS: ${{ matrix.os }}
          GOARCH: ${{ matrix.arch }}
          SVC_BIN_OUT_FILE: ${{ github.event.repository.name }}-${{ matrix.os }}-${{ matrix.arch }}
        run: go build -o ${{env.SVC_BIN_OUT_FILE}} main.go
      - uses: actions/upload-artifact@v4
        env:
          SVC_BIN_OUT_FILE: ${{ github.event.repository.name }}-${{ matrix.os }}-${{ matrix.arch }}
        with:
          name: ${{env.SVC_BIN_OUT_FILE}}
          path: ${{env.SVC_BIN_OUT_FILE}}
